language: node_js
node_js:
  - "4.2"
  - "4.3"
  - "4.4"
  - "4.5"
  - "4.6"
  - "4.7"
  - "4.8"
  - "5.12.0"
  - "6.9"
  - "6.10"
  - "7.3"
  - "7.7"
install:
  - npm install --all
script:
  - npm run lint
  - npm run test-cov
